export enum RmqMessages {
  // MEETUP MESSAGES
  GET_ALL_MEETUPS = 'GET_ALL_MEETUPS',
  GET_MEETUP_BY_ID = 'GET_MEETUP_BY_ID',
  CREATE_MEETUP = 'CREATE_MEETUP',
  UPDATE_MEETUP_BY_ID = 'UPDATE_MEETUP_BY_ID',
  DELETE_MEETUP_BY_ID = 'DELETE_MEETUP_BY_ID',
  SUBSCRIBE_TO_MEETUP = 'SUBCRIBE_TO_MEETUP',
  ELASTIC_SEARCH = 'ELASTIC_SEARCH',
  GET_MEETUP_BY_GEO = 'GET_MEETUP_BY_GEO',

  // TAG MESSAGES
  GET_ALL_TAGS = 'GET_ALL_TAGS',
  GET_TAG_BY_ID = 'GET_TAG_BY_ID',
  CREATE_TAG = 'CREATE_TAG',
  UPDATE_TAG_BY_ID = 'UPDATE_TAG_BY_ID',
  DELETE_TAG_BY_ID = 'DELETE_TAG_BY_ID',

  // AUTH MESSAGES
  CREATE_USER = 'CREATE_USER',
  LOGIN_USER = 'LOGIN_USER',
  VALIDATE_USER = 'VALIDATE_USER',
  LOGOUT_USER = 'LOGOUT_USER',
  REFRESH_TOKEN = 'REFRESH_TOKEN',

  // USER_MESSAGES
  GET_ALL_USERS = 'GET_ALL_USERS',
  GET_USER_BY_ID = 'GET_USER_BY_ID',
  DELETE_USER_BY_ID = 'DELETE_USER_BY_ID',

  // REPORT_MESSAGES
  REPORT_CSV = 'REPORT_CSV',
  REPORT_PDF = 'REPORT_PDF',
}
