export const RMQ_CONFIG = {
  SERVER_URL: process.env.RMQ_MEETUP_URL || 'amqp://localhost:5672',
  MEETUP_QUEUE: process.env.RMQ_MEETUP_QUEUE || 'MEETUP_QUEUE',
};

export enum RMQ_MODULES {
  MEETUP = 'MEETUP',
  TAG = 'TAG',
}

export enum RMQ_MESSAGES {
  GET_ALL_MEETUPS = 'GET_ALL_MEETUPS',
  GET_MEETUP_BY_ID = 'GET_MEETUP_BY_ID',
  CREATE_MEETUP = 'CREATE_MEETUP',
  UPDATE_MEETUP_BY_ID = 'UPDATE_MEETUP_BY_ID',
  DELETE_MEETUP_BY_ID = 'DELETE_MEETUP_BY_ID',

  GET_ALL_TAGS = 'GET_ALL_TAGS',
  GET_TAG_BY_ID = 'GET_TAG_BY_ID',
  CREATE_TAG = 'CREATE_TAG',
  UPDATE_TAG_BY_ID = 'UPDATE_TAG_BY_ID',
  DELETE_TAG_BY_ID = 'DELETE_TAG_BY_ID',
}
